### ISSUE TITLE
Issue: Naval Cannon damage not observable, unaffected by config file

### ISSUE THREAD

**Issue by Duskyth** [grilled-salmon/oldguns#23]
**Describe the bug**
I saw that the issue on players not being hurt was closed, but currently damage against entities for the base cannonball is nonexistent, this is regardless of any changes within the oldguns-server.toml file. Other cannonball types appear to function as intended, but edits to the server file do not effect the damage dealt. All  server file edits were tested with a singleplayer world

**Steps to reproduce the behavior:**
1. Place a naval cannon
2. Load and aim the naval cannon at a zombie or other entity (Range appears not to have an effect.)
3. Fire the cannon.
4. No observable damage on the entity (Through use of mods that allow observation of entity health, but confirmed to be accurate through use of weapons, Entity did receive knockback and the hurt effect but did not suffer any damage.)

**Expected behavior**
I expected the entity to experience observable damage that would change depending on edits to the oldguns-server.toml file.

**Screenshots**
Zombie health before blast (Upper right corner.)
![2022-07-01_22 53 56](https://user-images.githubusercontent.com/108560674/176985646-18e68a72-0e99-4b50-a637-16c75ba83642.png)

Loaded ammo (Large powder charge + normal medium cannonball.)
![2022-07-01_22 54 17](https://user-images.githubusercontent.com/108560674/176985703-83795346-70ad-4a05-be13-fffcf5e44116.png)

Zombie health post blast (No damage dealt.)
![2022-07-01_22 54 28](https://user-images.githubusercontent.com/108560674/176985685-66d73d4e-a865-47c6-8fac-5109aa362ec6.png)

**Mod Version**
[oldguns-1.18.2-3.3.0-26.jar]

**Mod List**
```
alexsdelight-1.18.2-1.2.3
alexsmobs-1.18.5
architectury-4.5.75-forge
AutoRegLib-1.7-53
AxesAreWeapons-1.5.2-forge-1.18.2
balm-3.1.0+0
BasaltWalker-1.18.2-1.3.1
bedspreads-forge-1.18.1-5.1.0.5
BetterThirdPerson-Forge-1.18.2-1.8.1
bygonenether-1.1.2-1.18.2
citadel-1.11.3-1.18.2
cloth-config-6.2.62-forge
Clumps-forge-1.18.2-8.0.0+10
collective-1.18.2-4.28
configured-1.5.3-1.18.2
create-mc1.18.2_v0.4.1
DamageTilt-1.18-forge-0.1.1
domesticationinnovation-1.4.2-1.18.2
eatinganimation-1.18.2-2.1.1
enchantmenttransfer-0.0.4-1.18.2
EyesInTheDarkness-1.18.2-1.2.7
FarmersDelight-1.18.2-1.1.2
feature_nbt_deadlock_be_gone_forge-2.0.0+1.18.2
flashnpcs-1.18.1-1.1.4v2
flytre_lib-1.18.2-1.8.2-forge
flywheel-forge-1.18-0.6.2
friendsandfoes-forge-mc1.18.2-1.4.5
glowinc-1.18.2_1.2.3
goblintraders-1.7.2-1.18.2
HerobrineAwakens-1.18.2-1.1.1-hf1
HunterIllager-1.18.2-4.0.1
iceologer-1-18-1
idas_forge-1.2.1+1.18.2
illagersweararmor-1.1.5
jei-1.18.2-9.7.0.209
JustEnoughResources-1.18.2-0.14.1.171
Kiwi-1.18.2-forge-6.1.2
lootbeams-1.18.1-release-jan1522
minecraft-comes-alive-7.3.4+1.18.2-forge
MouseTweaks-forge-mc1.18-2.21
musketmod-1.18.2-forge-1.4.3
NethersDelight-1.18.2-2.2.0
ohmygoat-forge-1.18.2-1.1.0
oldguns-1.18.2-3.3.0-26
Patchouli-1.18.2-71.1
Placebo-1.18.2-6.4.1
PuzzlesLib-v3.3.5-1.18.2-Forge
Quark-3.2-358
QuarkOddities-1.18
Quick Harvest-1.18.2-1.6.1
repurposed_structures_forge-5.1.14+1.18.2
selene-1.18.2-1.17.9
smartmend-v1.0.1-FORGE-1.17+
SnowRealMagic-1.18.2-forge-4.1.0
spawnermod-1.18.2-1.8.15+Forge
StackablePotions-forge-1.18.2-1.0.0
supplementaries-1.18.2-1.4.6
TaxFreeLevels-1.3.1-forge-1.18.1
TipTheScales-forge-1.18.2-5.0.6
ToastControl-1.18.2-6.0.2
torohealth-1.18-forge-2
TravelersTitles-1.18.2-Forge-2.1.1
TreeChop-1.18.2-0.15.7
UniversalBoneMeal-v3.0.5-1.18.2-Forge
villagebellrecipe_1.18.2-1.4
villagespawnpoint_1.18.2-1.9
waystones-forge-1.18.2-10.1.0
weeping_angels-1.0.1
worldedit-mod-7.2.10
WorldEditItems-v1.1.0-Forge-1.18.2
Xaeros_Minimap_22.3.0_Forge_1.18.2
XaerosWorldMap_1.23.1_Forge_1.18.2
XPFromHarvest-1.18.2-1.2.2
YungsApi-1.18.2-Forge-2.0.8
forge-1.18.2-40.1.54-universal.jar
```

**Additional context**
Another issue I noted is that the stack size command in oldguns-server.toml has zero effect in game, but as that is not the main subject of this report I'll just leave it here as a sidenote.

**Comment by Duskyth** [comment]
I forgot to mention, the explosive cannonballs do deal a direct 20 damage on impact regardless of configuration as well

**Comment by Duskyth** [comment]
I am also capable of killing my player with the cannon with the base iron medium cannonball loaded, with it working as intended, being an instant kill. Meanwhile the cannons have the opposite issue in 1.18.1, meaning that the change made to fix the lack of player damage is likely related to the result of no mob damage being dealt.

**Comment by Duskyth** [comment]
I can confirm it is either the BulletProjectile.class or BulletProjectile$1.class file causing the issue described in my report, I resolved this issue by copying the versions of these files from the 1.18.1 release into the 1.18.2 release and mob damage is now restored, albeit with the lack of player damage. The modifiers still do not work as assumed though.

**Comment by zach2039** [comment]
Thanks for reporting. Working on a fix now.

**Comment by zach2039** [comment]
Tested on mob and player, and it worked. Fingers crossed.
