### ISSUE TITLE
Cannot craft bark strands

### ISSUE THREAD

**Issue by titanicjames** [grilled-salmon/oldguns#24]
**Describe the bug**
No crafting recipes exist for bark strands.

**To Reproduce**
Nothing to reproduce.

**Expected behavior**
A method of crafting bark strands.

**Mod Version**
oldguns_v1.18.1-3.2.0-24.jar

**Mod List** //Excuse the mess, private modpack i cobbled together.
oldguns_v1.18.1-3.2.0-24.jar
jei-1.18.2-9.7.0.209.jar
appleskin-forge-mc1.18-2.4.0.jar
architectury-4.5.76-forge.jar
ChiselsBits-forge-1.18.2-1.2.101-universal.jar
ControlEngineering-0.1.1.jar
create-mc1.18.2_v0.4.1.jar
createchunkloading-1.1.0-forge.jar
create-confectionery1.18.2_v1.0.8.jar
createaddition-1.18.2-20220517a.jar
createdeco-1.2.7-1.18.2.jar
createplus-1.18.2_v0.4.0.0.jar
create-stuff-additions1.18.2_v1.1.6.jar
alloyed-1.18.2-v1.3d.jar (Create: Alloyed)
create-chromaticreturn1.18.2_v1.1.jar
create-factory-1.18.2-v1.6.jar
steampowered-1.18.2-2.0.3-alpha.jar (Create: Steampowered)
DungeonCrawl-1.18.2-2.3.9.jar
flywheel-forge-1.18-0.6.2.jar
ImmersiveEngineering-1.18.2-8.0.2-149.jar
ImmersivePosts-1.18.2-4.3.0-3.jar
industrializedcreate1.18.2_1.2.1.jar
journeymap-1.18.2-5.8.5-forge.jar
xercapaint-1.18.2-0.7.1.jar (Joy of painting)
JustEnoughResources-1.18.2-0.14.1.171.jar
markdown_manual-1.18.2-forge-1.2.1+59006bb.jar
MouseTweaks-forge-mc1.18-2.21.jar
xercamusic-1.18.2-1.0.0.jar (Music Maker Mod)
Patchouli-1.18.2-71.1.jar
theoneprobe-1.18-5.1.0.jar
tis3d-1.18.2-forge-1.6.8+2ac5c5f.jar

**Additional context**
Not much else, pretty much just saw this mod.

**Comment by zach2039** [comment]
Shears right-clicked on log will produce bark strands. Will add to guide book.

**Comment by titanicjames** [comment]
Dang, i thought it was done using the axe. That explains it.
