### ISSUE TITLE
Client Gun Crash

### ISSUE THREAD

**Issue by TheFallenChaos** [grilled-salmon/oldguns#29]
**Describe the bug**
A crash that occurs because of the firing of the Medium Naval Canon

**To Reproduce**
1. Place down "Medium Navel Gun"
2. Load it as you should
3. Fire it

**Expected behavior**
It should have fired the projectile (configs were untouched), the projectile would then come into contact with packed ice.

**Screenshots**
![image](https://user-images.githubusercontent.com/74574396/181402672-cf6648b9-558c-4217-bc13-a4d213df71b8.png)

**Mod Version**
oldguns-1.19-3.6.1-33

**Mod List**
![image](https://user-images.githubusercontent.com/74574396/181402784-badad49a-e211-49f0-b5ea-29e6913250c0.png)

**Additional context**
We're unsure why this is happening, this says nothing in our server console we are using to test the mod on, only that the crashed player is disconnecting.

**Comment by zach2039** [comment]
Do you have a client log or log of any type containing this message? Sometimes mixins/patches from some mods can have a hard-to-trace interaction with other mods; you can sometimes ascertain what mod is causing issues by the list of mixins in the log.

**Comment by TheFallenChaos** [comment]
Not any I could find, no

**Comment by SirCatZ** [comment]
copy pasta from another issue entry (but with the same problem):

One of my friends fixed this issue.
If i understood it correctly the mod already includes the code to stop distant clients from trying to render the bullets (which crashes the client when this chunks aren't loaded).
The error in the code is that the distance is entered wrong (the Minecraft documentation includes a wrong statement, so its not the creators fault (can't remember exactly, but something like if the value is already squared or not)).

i'll include the edited version we used (and tested successfully). Maybe the creator of the mod can later include the fix in an official version.

[oldguns-MODIFIED.zip](https://github.com/zach2039/oldguns/files/10299431/oldguns-MODIFIED.zip)

**Comment by zach2039** [comment]
Fixed in both [v3.6.3-38](https://github.com/zach2039/oldguns/releases/tag/v3.6.3-38) and [v3.7.1-39](https://github.com/zach2039/oldguns/releases/tag/v3.7.1-39) releases.
