### ISSUE TITLE
Issue with Old Guns 1.16.5

### ISSUE THREAD

**Issue by ItzPear** [grilled-salmon/oldguns#30]
There seems to be a strange issue with Old Guns 1.16.5 on servers, in which when you craft something, the server crashes.

1. Add Old Guns mod to a server
2. Attempt to craft something with the Gunsmith Bench
3. Crash

The expected behavior would be that you can normally craft with the Gunsmith Bench like in Singleplayer

**Mod Version**
1.16.5-3.0.6-23

**Mod List**
```
oldguns_v1.16.5-3.0.6-23.jar

...
```

The crash report is attached.
[crash-2022-08-02_01.44.23-server.txt](https://github.com/zach2039/oldguns/files/9245050/crash-2022-08-02_01.44.23-server.txt)

**Comment by zach2039** [comment]
Fixed with release v1.16.5-3.0.7-35
