### ISSUE TITLE
Guard Villagers crash the game when they try to shoot Old Guns muskets

### ISSUE THREAD

**Issue by ghost** [grilled-salmon/oldguns#34]
**Describe the bug**
Guard Villagers can be equipped with a gun from Old Guns, but when they attempt to point and shoot it at an aggressive mob like a zombie the game crashes and the save becomes unusable

**To Reproduce**
1. Install the mods (Old Guns, Guard Villagers, Patchouli).
2. Crouch+right click on an unemployed villager with a vanilla sword to make him a guard villager.
3. Open his inventory with right click and put an Old Guns musket in his weapon slot.
4. Spawn an aggressive mob like a zombie

**Expected behavior**
The guard villager will point the musket at the zombie and wait a moment as if aiming, and when he shoots, the game will crash and the save will not open.

**Screenshots**
![image](https://user-images.githubusercontent.com/102592228/185967456-e046cc97-d175-450f-b47d-9ab3fecda842.png)
![2022-08-22_17 06 02](https://user-images.githubusercontent.com/102592228/185967660-cb813f4a-1fd8-4aa9-8c02-5bf6d5c398f8.png)
![2022-08-22_17 06 18](https://user-images.githubusercontent.com/102592228/185967705-71d055b5-9744-4b14-ad81-d32c1058ae03.png)
![2022-08-22_17 06 26](https://user-images.githubusercontent.com/102592228/185967740-24bd18d6-fdb5-4d6f-8509-3b173bf86e1d.png)

**Mod Version**
1.18.2

**Mod List**
```
oldguns_v1.18.1-3.2.0-24.jar
guardvillagers-1.18.2.1.4.3.jar
Patchouli-1.18.2-71.1.jar
...
```

**Additional context**
sorry this took so long lol ask if u need any more info

**Comment by zach2039** [comment]
Fixed in both [v3.6.3-38](https://github.com/zach2039/oldguns/releases/tag/v3.6.3-38) and [v3.7.1-39](https://github.com/zach2039/oldguns/releases/tag/v3.7.1-39) releases, though the projectile spawned when fired is just an arrow. Will need some help from Guard Villagers' author on how best to tie in proper functionality.
