### ISSUE TITLE
Crash when a bullet hits an entity

### ISSUE THREAD

**Issue by auctumnus** [grilled-salmon/oldguns#39]
The server and client crash whenever a bullet hits an entity.

Minecraft version is 1.18.2, mod version is 3.3.1-27.

Here's the crash report:
[crash-2022-12-26_11.58.15-server.txt](https://github.com/zach2039/oldguns/files/10304151/crash-2022-12-26_11.58.15-server.txt)

**Comment by zach2039** [comment]
Fixed with [3d86e20](https://github.com/zach2039/oldguns/commit/3d86e20d42ac1aad5de21dca92962fe4670cd461), release tag v1.18.2-3.3.2-36
