### ISSUE TITLE
Crash when crafting shapeless recipes in Create's basin and mixer.

### ISSUE THREAD

**Issue by Taser-Tater** [grilled-salmon/oldguns#49]
**Description:**

When attempting to make medium grade black powder in a Create mixer, the game will crash with exit code -1.

**To Reproduce:**
1. Build mixer, and power it with a mechanical generator of some sort.
2. Insert mortar and pestle, niter, sulfur, and charcoal.
3. Game will crash almost immediately.

**Expected Behavior:**

Game not crashing, medium grade black powder produced in the basin.

**Screenshots:**

A Create Mixer
![image](https://github.com/zach2039/oldguns/assets/137655817/2033c8f8-63ef-4231-a100-e623d78f03ba)

Mixer Basin, containing all of the ingredients for medium grade black powder except charcoal. When the charcoal is added, the game will crash.
![image](https://github.com/zach2039/oldguns/assets/137655817/772bcc4d-5bad-4e82-8eb1-dbc5b9295ac9)

**Mod Version:**

1.19.2-3.7.2-42

**Mods List:**

ars_nouveau-1.19.2-3.17.3.jar
Cucumber-1.19.2-6.0.7.jar
CyclopsCore-1.19.2-1.18.6.jar
mcw-bridges-2.1.0-mc1.19.2forge.jar
mcw-paths-1.0.3forge-mc1.19.2.jar
mcw-roofs-2.2.4-mc1.19.2forge.jar
moonlight-1.19.2-2.2.40-forge.jar
MysticalAgriculture-1.19.2-6.0.10.jar
oculus-mc1.19.2-1.6.4.jar
oldguns-1.19.2-3.7.2-42.jar
rubidium-0.6.2b.jar
supplementaries-1.19.2-2.3.19.jar
appleskin-forge-mc1.19-2.4.2.jar
Aquaculture-1.19.2-2.4.8.jar
architectury-6.5.85-forge.jar
bettercombat-forge-1.7.1+1.19.jar
chipped-forge-1.19.2-2.1.5.jar
cloth-config-8.2.88-forge.jar
CTM-1.19.2-1.1.6+8.jar
create-1.19.2-0.5.1.b.jar
curios-forge-1.19.2-5.1.4.1.jar
dungeonsweaponry-1.11.0-1.19.2.jar
ExplorersCompass-1.19.2-1.3.0-forge.jar
ExtraArmor 1.19.2-1.17.1.jar
FarmersDelight-1.19-1.2.1.jar
geckolib-forge-1.19-3.1.40.jar
gravestone-1.19.2-1.0.1.jar
Jade-1.19.1-forge-8.8.1.jar
journeymap-1.19.2-5.9.7-forge.jar
jei-1.19.2-forge-11.6.0.1015.jar
mcw-doors-1.0.9forge-mc1.19.2.jar
mcw-fences-1.0.7-mc1.19.2forge.jar
mcw-furniture-3.1.0-mc1.19.2forge.jar
mcw-lights-1.0.5-mc1.19.2forge.jar
mcw-paintings-1.0.4-mc1.19.2.jar
mcw-trapdoors-1.1.0-mc1.19.2forge.jar
mcw-windows-2.1.1-mc1.19.2forge.jar
MouseTweaks-forge-mc1.19-2.23.jar
NaturesCompass-1.19.2-1.10.0-forge.jar
OreExcavation-1.11.166.jar
Patchouli-1.19.2-77.jar
player-animation-lib-forge-1.0.2.jar
polymorph-forge-0.46.1+1.19.2.jar
ResourceChickens-1.19.2-1.4.jar
resourcefullib-forge-1.19.2-1.1.24.jar
simplyswords-forge-1.46.0-1.19.2.jar
TerraBlender-forge-1.19.2-2.0.1.136.jar

**I am aware that several of these mods are out of date, including Old Guns. I have tested this issue with all of the mods up to date, and the issue still persists.**
I hope that this crashing issue can be solved as being able to make an ammo factory with Old Guns and Create would be very cool.

**Crash Report:**
[crash-2023-06-24_18.18.28-server.txt](https://github.com/zach2039/oldguns/files/11858322/crash-2023-06-24_18.18.28-server.txt)

**Comment by Taser-Tater** [comment]
oops my bad

**Comment by zach2039** [comment]
Fixed for 1.19.2 with [v3.7.3-47](https://github.com/zach2039/oldguns/releases/tag/v3.7.3-47).

Fix is pending for 1.19.4.
