### ISSUE TITLE
serverconfig does not work

### ISSUE THREAD

**Issue by YackMyGack** [grilled-salmon/oldguns#58]
Whenever I try to change things with the serverconfig, the changes are reset to default and the config creates a BAK file. When putting a modified file into the defaultconfigs folder (like how the oldguns-common file says to do) nothing happens.

1.18.2-3.3.3-40.3

**Comment by zach2039** [comment]
Fixed for 1.18.2 with [v3.3.4-44](https://github.com/zach2039/oldguns/releases/tag/v3.3.4-44)

Fix for 1.19.4 is pending.

**Comment by zach2039** [comment]
Fixed for 1.19.4 with [v3.8.1-45](https://github.com/zach2039/oldguns/releases/tag/v3.8.1-45), at least with firearm attributes.

Crafting control will take more work, and might need to be removed in lieu of ct or kubejs, which are better suited for crafting edits. Will track crafting control separately.
