### ISSUE TITLE
Mod request/idea/shrug

### ISSUE THREAD

**Issue by insidjs** [grilled-salmon/oldguns#9]
Standalone mod that includes the naval cannon 

unique features:
-remove gunners compass to disable the cannon rotation
-2-3 different charges for different ranges, (all same velocity)
         -1 charge half the distance of the current default charge
         -1 charge double the distance of the current default charge
         -1 charge for triple the distance of the current charge 

other ideas: (completely up to you)
-increase the explosiveness of the current medium cannonball without increasing explosion size (e.g. can break everything up to endstone) (or have an Armor Penetrating cannonball for that)
-grapeshot? 
-nerfing HE radius as currently it is a bit ridiculous

**Comment by zach2039** [comment]
Most of these implemented in v1.18.1 versions of the mod.
